### PR TITLE
replace bad characters when exporting a contact

### LINKED ISSUE #1368: Cannot import or share contact
### Illustrations

- Device: N5
- Channel: devel
- Build: today's build

### Steps to reproduce

From contact app, select a contact and try to share it
From messaging-app, try to import a contact as an attachment

### Expected behavior

Contact is imported/exported 

### Actual behavior

Screen is stuck with the "load" popup

### Logfiles and additional information

in address-book log:
file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/AddressBook/Base/ContactExporter.qml:123: TypeError: Cannot read property 'Aborted' of undefined

undefined refers to `ContentTransfer` in the code.
Note that from messaging-app, if you select multiple contact, it works...

### PR DESCRIPTION
**Pull request by lduboeuf**
this fix https://github.com/ubports/ubuntu-touch/issues/1368

### CODE REVIEW

**Review by Flohack74 — APPROVED** [review]

**Comment by farkasdvd** [comment]
Device: bq e5
Image: 2020-W35/2

I exported one of my favorite contacts from address-book-app to messaging-app. Then I tried to import another contact to messaging-app via attachments, however it showed only my favorite contacts and there was now way to switch to all contacts. On the 2nd try it showed all my contacts correctly.

I played with it for few more minutes and this happened. I was exporting 2 contacts 1 by 1 to messaging-app and the 1st contact (which was already imported) was replaced by these red contacts:

contact_import

**Comment by lduboeuf** [comment]
note that this PR only fix the contact export  that have `/` in the name

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W35/2

Exporting contact with ```/``` in name works.

I've created an contact with unusual name ```tmpðまžč/\~@#€<>[]`^¡¿„”"“"«»/|\``` and with such atrocity in some fields. The contact app didn't freeze when exported the contact.

However, if an contact is exported to file (through ```File manager```), the name of the file will be ```Name_Surname.vcf```. In my test contact case, the filename becomes ```tmpðまžč/_%5C~@``` (without suffix). Such file is not importable again and needs to be renamed before import (tmp.vcf worked). When exporting this contact to message app, the atachment no longer has avatar from contacts (image or rectangle with letter(s)), but an paper clip (:paperclip:).

**Comment by lduboeuf** [comment]
That's an intersting test ;-).
Well this is not a regression as it was already the case before. So feel free to file a bug.

**Comment by jezek** [comment]
> That's an intersting test ;-).

Yeah, my brother's name was always a little bit challenging for applications with poorly handled inputs :laughing: ([just kidding](https://xkcd.com/327/)). Issue filled #155 

But I forgot the ```'``` character in test string.
If you change the name to eg. ```o'name```, the export will hang.

**Comment by Flohack74** [comment]
So the original issue is fixed now just to confirm?

**Comment by lduboeuf** [comment]
at least for the '/' that make the export not working, it works

**Comment by jezek** [comment]
@Flohack74 Yes, the original issue is fixed. The new found apostrophe (```'```) issue is filled under #157

**Pull request merged**
