### PR TITLE
enable build with clickable

### LINKED ISSUE #118: Unable to build from clickable
clickable
Sending build context to Docker daemon  3.584kB
Step 1/3 : FROM clickable/ubuntu-sdk:16.04-armhf
 ---> a6eb470aafc3
Step 2/3 : RUN echo set debconf/frontend Noninteractive | debconf-communicate && echo set debconf/priority critical | debconf-communicate
 ---> Using cache
 ---> f600430542a1
Step 3/3 : RUN apt-get update && apt-get install -y --force-yes --no-install-recommends libqofono-dev:armhf ofono-dev:armhf intltool:armhf pkg-config:armhf qt5-default:armhf qtbase5-dev:armhf qtdeclarative5-dev:armhf qtpim5-dev:armhf qml-module-ofono:armhf qtdeclarative5-buteo-syncfw0.1:armhf qtdeclarative5-gsettings1.0:armhf qtdeclarative5-ubuntu-history0.1:armhf qtdeclarative5-ubuntu-keyboard-extensions0.1:armhf qtdeclarative5-ubuntu-telephony-phonenumber0.1:armhf qtdeclarative5-qtcontacts-plugin:armhf qml-module-qtquick2:armhf qtdeclarative5-qtcontacts-plugin:armhf && apt-get clean
 ---> Using cache
 ---> 6a2591c019e7
Successfully built 6a2591c019e7
Successfully tagged clickable/ubuntu-sdk:16.04-armhf-c2cc1906-9466-4a8e-b06e-70b5c261fd48
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Autopilot tests disabled: autopilot binary not found
-- Found PkgConfig: arm-linux-gnueabihf-pkg-config  
-- Checking for module 'libqofono-dev'
--   /usr/bin/pkg-config: 1: /usr/bin/pkg-config: Syntax error: word unexpected (expecting ")")
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:25 (pkg_check_modules)
 
 
-- Configuring incomplete, errors occurred!
See also "/home/ruben/Transferências/address-book-app-master/build/arm-linux-gnueabihf/app/CMakeFiles/CMakeOutput.log".
Command exited with non-zero exit status 1, see above for details. This is most likely not a problem with Clickable.

### PR DESCRIPTION
**Pull request by lduboeuf**
fix https://github.com/ubports/address-book-app/issues/118

### CODE REVIEW

**Comment by Flohack74** [comment]
@bhdouglass is there any reason we cannot move that app to Gitlab? I would prefer to having this done for all that we can move ;) - Enabling clickable could be welcomed occasion.

**Comment by bhdouglass** [comment]
Yeah if we can start building and shipping this as a click we can definitely move it over to gitlab.

**Comment by lduboeuf** [comment]
please review before, i did a lot copy/paste things and could make it dangerous ( i was just thinking of make it quick testable )

**Comment by lduboeuf** [comment]
note that currently contact export store files in /tmp dir , see apparmor write-dir property
Edit: see 745edd1 , now store temp export file to default app cache dir

**Comment by lduboeuf** [comment]
humm "module "Qt.labs.platform" is not installed" error on tests

**Comment by lduboeuf** [comment]
not sure we can build and ship it independently , or we would need to split it in 2 repos ( contact modules and the app ). For now it is good for testing locally and giving it as a click for testers

**Comment by lduboeuf** [comment]
@maintainers, can we merge that feature, as it makes easy to test the app now?
AFAIK there is no side effects on the current build system

**Comment by lduboeuf** [comment]
humm, that is strange, i have this now : 

> [ 49%] Generating nb.gmo
/bin/sh: 1: Syntax error: "(" unexpected
po/CMakeFiles/address-book-app.pot.dir/build.make:57: recipe for target 'po/CMakeFiles/address-book-app.pot' failed
make[2]: *** [po/CMakeFiles/address-book-app.pot] Error 2
CMakeFiles/Makefile2:2201: recipe for target 'po/CMakeFiles/address-book-app.pot.dir/all' failed
make[1]: *** [po/CMakeFiles/address-book-app.pot.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target pofiles_67

 it used to work before ( that happens when i've added the `ALL`  to the CMakeList ( see last commit )), so for now i can't make clickable update the pot file, if anyone can help on it

**Comment by jwillikers** [comment]
The patch works for me when I run `clickable`.
I can't get `clickable desktop` to work though.

**Comment by lduboeuf** [comment]
yes, but running address-book-app with `clickable desktop` will need to install a big part of the system inside the container (database, all qml dependencies, services  and so on).
I'm afraid it is not doable easily.
EDIT: UI seems to be testable with my local test, i will add something to that PR
EDIT again: add issues then with only `clickable` ...

**Comment by lduboeuf** [comment]
okay so i had success running `clickable desktop` but the required dependencies cause issues when building for the device.
Apart from maintaining one clickable.json and another one for desktop, i don't know how to handle that. Any hints welcome.
I'm stuck with `qtcontact5-galera` dependency needed to run in desktop, but that lead to conflicting packages when building for device.

**Comment by lduboeuf** [comment]
@jwillikers please try again for desktop mode if it is ok, see last commit
So at least UI in desktop is testable

**Comment by jwillikers** [comment]
@lduboeuf I will test this in few hours and let you know.

**Comment by jwillikers** [comment]
@lduboeuf This builds correctly with `clickable desktop` however I appear to have an issue running it which is most likely just related to my setup.

#### Update:
Nvidia fixed their container runtime with an update and now `clickable desktop` builds and runs the application successfully! 😆

**Review by Flohack74 — APPROVED** [review]

**Comment by Flohack74** [comment]
@lduboeuf plz resolve conflicts here ^^

**Pull request merged**
