### PR TITLE
add export all contacts action in settings

### PR DESCRIPTION
**Pull request by lduboeuf**
testable here: https://drive.google.com/open?id=1JVPkuDY10Qh7fEYkUAIskuR2c9K7b2ah

### CODE REVIEW

**Review by Flohack74 — APPROVED** [review]

**Comment by j2g2rp** [comment]
Is this implemented on last releases of devel?
In my case I see that there is a new text that says: Reading my phone number(s)... 
But it didn't change. I don't know if it is unexpected.

By other way. The new strings aren't translatable yet, are they?

**Comment by lduboeuf** [comment]
did you have your phone number displayed before this update ?
And yes it should be translatable as i updated the translation file but don't know the sync process with weblate

**Comment by j2g2rp** [comment]
Where my phone number should be?
Thanks for the info about the translations. Ill translate them once are synced.

**Comment by Flohack74** [comment]
@j2g2rp translations are broken atm, sorry for that...

**Comment by lduboeuf** [comment]
> Where my phone number should be ?

In address-book-settings

It is possible that some phone numbers are not read from the SIM because not set

**Comment by farkasdvd** [comment]
Device: bq e5
Image: 2020-W35/2

Works as expected.

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W35/2

Works.

**Comment by abkro** [comment]
Device: Nexus 5
Image: 2020-W35/2

Chose 'export all contacts' followed by 'file manager'. The file manager opened and the spinner went on for a few seconds, but nothing appeared. I searched around in the different folders, too, but I saw nothing. (To be clear, I entered my PIN-password when prompted before searching the folders.) But maybe I have misunderstood how it is supposed to work?

**Comment by jezek** [comment]
@abkro After file manager opens (after spinner), choose directory, where you want to save and hit the check button (:white_check_mark:) in top right corner to save, or the cross (:negative_squared_cross_mark: ) to abort saving.  (Maybe there should be text near the buttons).

**Comment by abkro** [comment]
@jezek Thank you. That worked. The contacts export file was produced, so I guess this works as intended.

**Comment by padu22** [comment]
I noticed that exporting contacts via UI leads to noticeably smaller files than exporting via

    $ syncevolution --export /home/phablet/Documents/utcontacts.vcf backend=evolution-contacts

Further inspections shows that records from the shell command contain some more optional (`REV`, `UID`) plus some non-standard [vcard fields](https://en.wikipedia.org/wiki/VCard#Properties).  While I don't care about the non-standard ones, I do wonder if dropping the former is intentional.

Granted, when importing contacts from a .vcf file, I think an application should not use existing information from fields `REV` and `UID`.  That is, it would better create unique UIDs itself and set last modification time to the time of the import.  Though, during export, I'd perhaps not drop those fields as the information may be of interest (for `REV`).  Or it could make life easier when doing some further processing of an exported .vcf file (for `UID`).  Think of two intentionally identical, e.g., sparsely filled, contacts that have different UID.  UT contacts app would show those as two distinct contacts.  But after UI export, that explicit information is missing.

I'm not saying the current behaviour is wrong.  After all `REV` and `UID` are optional fields only.  But I'm not convinced either dropping is the best way to handle `REV` and `UID` fields during export.

**Comment by lduboeuf** [comment]
mpressive report ;-). The "export all" feature here is just a shortcut of an existing feature, ( nothing have been done new on backend for vcf export ). So it should more be reported as an external issue IMO.

**Comment by padu22** [comment]
What is that existing feature?  It's obviously not equivalent to the given shell command.  Has there already been another UI way to export contacts?

**Comment by lduboeuf** [comment]
You already can export all contacts by long pressing on a contact and tick the select all icon and then export.
But yes if vcf extraction can be improved, just file a bug

**Comment by padu22** [comment]
OK, didn't know that. :-)  Will file another bug.

Except for the missing translations, this feature looks fine, otherwise.

**Pull request merged**
