### PR TITLE
add import contact from vcf file

### LINKED ISSUE #8: Expose vcf import in interface
A report at [this forum thread[(https://forums.ubports.com/topic/420/successful-ubports-installation-and-contacts-import-on-nexus-5/2) states that .vcf files cannot be imported from within the Contacts app, but opening them from the file manager is possible.

Provide an option in the interface to browse for and import vcard files at will.

### PR DESCRIPTION
**Pull request by lduboeuf**
fixes https://github.com/ubports/address-book-app/issues/8

testable here: https://drive.google.com/open?id=1JVPkuDY10Qh7fEYkUAIskuR2c9K7b2ah

### CODE REVIEW

**Comment by lduboeuf** [comment]
As suggested by Steven Berson on TG, would be nice to have already this feature at initial startup

**Comment by Flohack74** [comment]
Is this gonna import stuff via ContentHub?

**Comment by lduboeuf** [comment]
yes

**Comment by hummlbach** [comment]
uh nice, yes this feature was a bit hidden up to now causing a lot of questions

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
