### PR TITLE
add swipe actions on contact list items

### LINKED ISSUE #86: Contact list items do not support swipe actions
The current contact items cannot be swiped left or right, as expected from the system experience. I was just struggling to delete a contact, by swiping it right.
At least the delete option for a single contact should be available there. Also maybe on swipe left you could have a forward/share option.

### PR DESCRIPTION
**Pull request by lduboeuf**
This allow individual contact deletion by swiping right and share action by swiping left:
fixes https://github.com/ubports/address-book-app/issues/86

### CODE REVIEW

**Comment by lduboeuf** [comment]
should we add the send sms action also ?

**Comment by Flohack74** [comment]
Yes, why not, since now it kinda needs a lot of clicks until you can send an SMS

**Comment by lduboeuf** [comment]
ok, done, added call and sms action. And allow to select one phoneNumber when there is more than 1 number

**Comment by lduboeuf** [comment]
how does work translation on this repo ?

**Comment by Flohack74** [comment]
translate.ubports.com will pick up a change to the pot file. So you need to commit any changes that your build has created in the pot file :)

**Comment by lduboeuf** [comment]
humm ok, so it seems that clickable don't build the pot file.

**Comment by lduboeuf** [comment]
testable here: https://drive.google.com/file/d/1JVPkuDY10Qh7fEYkUAIskuR2c9K7b2ah

**Review by Flohack74 — APPROVED** [review]

**Comment by Flohack74** [comment]
Plz resolve conflikcts here too ^^

**Comment by lduboeuf** [comment]
so i guess all following PR that include a pot file will have a merge conflict :-|, can't we make CI doing the pot file regeneration when merging ?
So will wait for that one to be merged and rebase the next PR in conflict (#128) afterward

**Comment by Flohack74** [comment]
Hmm sorry no, the CI cannot be instructed to regenerate the pot file easily. It would need to commit to the repository after the build, and thats not what CI does normally. Rather than the devs must fight it out who does pot updates, since also sometimes a build triggers a no-change pot modification due to just reordering the lines ^^

**Comment by Fuseteam** [comment]
seems to work fine on BQE5
tho it doesn't work when accessed from the dialer app is that expected?

**Comment by Flohack74** [comment]
Good question. @lduboeuf  ?

**Comment by lduboeuf** [comment]
> tho it doesn't work when accessed from the dialer app is that expected?

yes, as it needs to be added there too. Dialer-app re-use only a part of the UI from address-book-app.
Btw, i've done something about it here: https://github.com/ubports/dialer-app/pull/127

**Comment by Fuseteam** [comment]
cool thanks @lduboeuf

**Comment by ghost** [comment]
@lduboeuf works fine with FP2, except for the call action. That is the case for people with several phone numbers, as well as people with only one phone number, sadly.
Edit : tested the call action again, it works, it was I who badly aimed for the icon...

**Comment by laborim** [comment]
Device: Oneplus 3
Build: 2020-W36

Works as expected from Contacts app. Still doesn't work from Dialer.

**Comment by lduboeuf** [comment]
@laborim what do you mean by "Still doesn't work from Dialer." ?

**Comment by laborim** [comment]
If I open Contacts app from Dialer only apears call button if I swipe left and no action if I try to swipe right on a contact.

If I open directly from Contact app icon apears delete button if I swipe right and share, message and call if I swipe left.

**Comment by lduboeuf** [comment]
Oh ok, yes i've only implemented call function in dialer-app, because if it uses the same layout, some logic need to be implemented in dialer app too. I thought it was sufficient to only bring the call feature. So can be a feature request in dialer-app for later

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W36

Works as described by @laborim

**Pull request merged**
