### PR TITLE
fix ActionButton having disabled style

### PR DESCRIPTION
**Pull request by lduboeuf**
Action Buttons such as message or call have some disabled-like style

Before:

screenshot20200715_213425876

After:

screenshot20200715_215344852

### CODE REVIEW

**Comment by lduboeuf** [comment]
@cibersheep what do you think ?

**Comment by cibersheep** [comment]
Yep. Looks better now... more «active» :)

**Comment by cibersheep** [comment]
This might fix https://github.com/ubports/address-book-app/issues/33 ?
Or we have to address that in a different manner?

**Comment by lduboeuf** [comment]
> This might fix #33 ?

yes it should ( haven't tested in dark though )

**Comment by lduboeuf** [comment]
@cibersheep : Humm sadly not, when we have a light background, you don't see well the star

**Comment by cibersheep** [comment]
I see... we need to adapt the design then

**Comment by Flohack74** [comment]
Should we still merge it?

**Comment by lduboeuf** [comment]
that is needed yes. Another work need to be done for the favorite icon on another PR

**Review by Flohack74 — APPROVED** [review]

**Comment by ghost** [comment]
Works fine with FP2, thank you very much :)

**Comment by farkasdvd** [comment]
Device: bq e5
Image: 2020-W35/2

LGTM

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W35/2

Works on dark theme.

**Comment by abkro** [comment]
Device: Nexus 5
Image: 2020-W35/2
Looking good.

**Comment by laborim** [comment]
Device: OP 3
Build: 2020-W35/2

Works as expected in both light and dark theme

**Comment by cibersheep** [comment]
Works as expected Ambiance and SuruDark E5HD RC

**Pull request merged**
