### PR TITLE
make favorite icon visible

### PR DESCRIPTION
**Pull request by lduboeuf**
ref: https://github.com/ubports/address-book-app/issues/33

### CODE REVIEW

**Comment by cibersheep** [comment]
I was thinking to use something like the uuitk buttons do with the text (change depending on the background) but that might be difficult to implement (?)

**Comment by lduboeuf** [comment]
> I was thinking to use something like the uuitk buttons do with the text (change depending on the background) but that might be difficult to implement (?)

I don't know ;-), but i will give a try since that change in UI have side effects for the logic inside ( the tests are failing )
Can you point me to an example ?

**Comment by cibersheep** [comment]
Now the button on a text is compairing background and decide if text should be clear or dark: https://github.com/ubports/ubuntu-ui-toolkit/blob/xenial/src/imports/Components/Themes/Ambiance/1.3/ButtonStyle.qml#L166

I don't know how to get the color of the image under the icon. I'm thinking that we might add a transparent layer...

imatge

**Comment by lduboeuf** [comment]
ok, so by using a LinearGradient, it could be fine:
screenshot20200723_100758970
screenshot20200723_100725716

**Comment by lduboeuf** [comment]
with a little gradient tuning:
screenshot20200723_101600738
screenshot20200723_101515819

**Comment by cibersheep** [comment]
Yep. Looks that works

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
