### PR TITLE
UbuntuColor to theme palette

### PR DESCRIPTION
**Pull request by cibersheep**
- UbuntuColors to theme palette counterparts
- Clear import cancel button

* I couldn't trigger the pot update

### CODE REVIEW

**Comment by Flohack74** [comment]
I will have a look at those pot thingies. Please ping me on the evening.

**Comment by cibersheep** [comment]
We tried but couldn't manage to update the pot. 
Need is welcome

**Comment by Flohack74** [comment]
How did you do that Dalton ;)

**Review by Flohack74 — APPROVED** [review]

**Comment by cibersheep** [comment]
L O V E

**Pull request merged**
